mod access_invisible_test;
mod assign_type_mismatch_test;
// mod await_in_sync_test;
mod cast_type_mismatch_test;
mod check_return_count_test;
mod code_style;
mod disable_line_test;
mod duplicate_field_test;
mod duplicate_index_test;
mod duplicate_require_test;
mod enum_value_mismatch_test;
mod generic_constraint_mismatch_test;
mod global_in_non_module_test;
mod incomplete_signature_doc_test;
mod inject_field_test;
mod luaconfig;
mod missing_fields_test;
mod missing_parameter_test;
mod need_check_nil_test;
mod param_type_check_test;
mod readonly_check;
mod redefined_local_test;
mod redundant_parameter_test;
mod require_module_visibility_test;
mod return_type_mismatch_test;
mod syntax_error_test;
mod unbalanced_assignments_test;
mod undefined_doc_param_test;
mod undefined_field_test;
mod undefined_global_test;
mod unknown_doc_tag;
// mod unnecessary_assert_test;
// mod unnecessary_if_test;
mod unused_test;
